swift-deploy: Check arguments
Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/swift-deploy b/swift-deploy
--- a/swift-deploy
+++ b/swift-deploy
@@ -3,5 +3,28 @@
 cwd="${0%/*}"
 cd "$cwd"
 
-./swift-inventory "$1" .
-ansible-playbook -i layout.ini site.yml
+case "$#" in
+	0)
+		printf 'Usage: swift-deploy /path/to/layout.conf /output/path\n' >&2
+		exit 1
+		;;
+	1)
+		printf 'Error: More arguments required\n' >&2
+		exit 1
+		;;
+	[3-9]*)
+		printf 'Error: Too many arguments\n' >&2
+		exit 1
+		;;
+esac
+
+layout="$1"; shift
+output="$1"; shift
+
+if [ ! -f "$layout" ]; then
+	printf '%s: File not found\n' "$layout" >&2
+	exit 1
+fi
+
+./swift-inventory "$layout" "$output"
+ansible-playbook -i "$output"/layout.ini site.yml
